### ISSUE TITLE
Cannot aim down sights of the new (McShay weapon pack 2) guns when using this mod

### ISSUE THREAD

**Issue by Swagmaster2033** [simon-wh/PAYDAY-2-BeardLib#574] opened 2022-09-22 00:07 UTC
When i have the mod installed, i can't aim with the Kahn .357, VD-12, and Hailstorm Mk5

**To Reproduce**
open game (with beardlib on
equip the Kahn .357, VD-12, or Hailstorm Mk5
start a heist
press mouse 2

**Comment by segabl** [comment] 2022-09-22 15:15
Can not reproduce this, do you have other mods that could cause conflicts, like WeaponLib?

**Comment by segabl** [comment] 2022-10-16 22:48
Closing this as this was most likely caused by the eyeAim mod, which should be fixed now.

**Closed** 2022-10-16 22:48 UTC
Labels: bug
