### ISSUE TITLE
Crash issue on Rats day 3, Big Bank

### ISSUE THREAD

**Issue by ReiyoTheRice** [simon-wh/PAYDAY-2-BeardLib#640] opened 2023-04-17 17:27 UTC
Year ago I've uploaded this crash report but since multiple other problems came up and I hadn't had time to care about it, I just forgot. But here I'm year after that with the same issue.
Description:
On rats, the game just crashes after finishing up day 2 and trying to load in day 3 (sadly i have no crash log for that one since it takes so long to reproduce). But on big bank the game crashes in first 50 seconds of the game. This doesnt occur if the host doesn't have beardlib installed or the person joining. 

Start up day 3 of rats with atleast one other player (both you and him) having beardlib installed. Same goes for big bank heist. 

Crashlog:
Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:61: attempt to call method 'synch_equipped_weapon' (a nil value)

SCRIPT STACK
@mods/PAYDAY-2-BeardLib-master/Hooks/Network/NetworkHooks.lua:94

But this time I've downloaded the custom beardlib variant I was provided in the year old thread and this is the crashlog in payday2/mods/logs -
07:15:53 PM Lua: [ERROR] Trying to sync weapon to a unit that does not possess a synch_equipped_weapon function (userdata: 0x00000bbe)
Unit inventory is CopInventory
07:16:02 PM Log:  (C:\projects\payday2-superblt\src\http\http.cpp:44) CURL CLOSED
07:16:02 PM Log:  (C:\projects\payday2-superblt\src\xaudio\XAudio.cpp:147) Closing OpenAL XAudio API
+ attached file of what the game said about the crash
![asdasd](https://user-images.githubusercontent.com/105747688/232563173-fdae3cf7-e7ac-4498-922a-a29574af4c74.png)

**Comment by segabl** [comment] 2023-04-18 09:36
Haven't seen this issue yet but will look into what might cause it. In the meantime you should check if you'Re using any other mods that may mess with weapons in any way

**Comment by ReiyoTheRice** [comment] 2023-04-18 14:50
Even if i remove everything besides BLT and Beardlib game still crashes

**Comment by ReiyoTheRice** [comment] 2023-04-18 15:44
Okay so
I'm dumb, I forgot that custom maps are technically mods too so we removed them and guess what, It doesn't crash anymore. Atleast it looks like so, I've had time to test out big bank only before my friend had to go and since its multiplayer related crash, I cannot test it solo. But most likely it should be fixed

**Comment by segabl** [comment] 2023-04-20 09:35
Would be nice to know which custom map causes this but seems like it doesn't self contain its changes to only happen when that map is played

**Comment by ReiyoTheRice** [comment] 2023-04-20 12:24
To be honest, I dont know. I know it sounds stupid but well my friend had those maps installed, not me and he kinda just threw them out of the window the moment I told him to disable them but one of them was probbably this map https://modworkshop.net/mod/27580 - Bink bank + - probbably. From what he said i figured he had 2 big bank maps and I couldnt find any other that we would had have downloaded so it's probbably this one. And I have no idea what caused crash on other maps but well I cant even figure it out since he removed all of the custom ones.

**Comment by segabl** [comment] 2023-04-27 11:45
likely an outdated custom map then, closing this as not caused by beardlib itself

**Closed by segabl** 2023-04-27 11:45 UTC
Labels: crash
