### ISSUE TITLE
can not PLAY PAYDAY2

### ISSUE THREAD

**Issue by himurabattousa** [simon-wh/PAYDAY-2-BeardLib#439] opened 2021-07-31 12:53 UTC
Sat Jul 31 21:42:49 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:236  
                   LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:258  
             safe_spawn_unit()  @mods/BeardLib/Hooks/CoreSystem.lua:26              
                        init()  core/lib/managers/mission/coreelementunitsequence.lua:10  
                         new()  core/lib/utils/coreclass.lua:35                     
            _create_elements()  core/lib/managers/mission/coremissionmanager.lua:457  
                        init()  core/lib/managers/mission/coremissionmanager.lua:403  
                         new()  core/lib/utils/coreclass.lua:35                     
itr_original_missionmanager_addscript()  core/lib/managers/mission/coremissionmanager.lua:113  
                 _add_script()  @mods/Iter/lua/coremissionmanager.lua:603           
          _load_mission_file()  core/lib/managers/mission/coremissionmanager.lua:107  
                       parse()  core/lib/managers/mission/coremissionmanager.lua:78  
                    original()  lib/setups/gamesetup.lua:684                        
                   init_game()  @mods/base/req/core/Hooks.lua:260                   
                                core/lib/setups/coresetup.lua:422

**Comment by himurabattousa** [comment] 2021-07-31 12:54
All mods are not recognized anymore.

**Comment by Luffyyy** [comment] 2021-08-01 08:45
Same as I said to the other person in #445, please explain in more detail so I can help you. Please include your BLT log (mods/logs)

**Comment by GregoryMonteiro** [comment] 2021-08-01 12:17
Are logs really needed?
Just download [Iter](https://pd2mods.z77.fr/iter.html) and play 5 minutes it will crash

**Comment by Luffyyy** [comment] 2021-08-01 12:53
Yes, they are. It takes a second to upload.

**Comment by Iamgoofball** [comment] 2021-08-01 20:47
Iter is extremely old and outdated. That crash could absolutely be caused by Iter.

**Comment by GregoryMonteiro** [comment] 2021-08-02 14:20
@Luffyyy @Iamgoofball 
The "extremely old and outdated" mod works on BeardLib version 4.41 without crashing.
Something you did that made it stop working.
They could just solve it by installing the mod and seeing the problem that happens.

**Comment by Luffyyy** [comment] 2021-08-02 16:39
I'm not trying anything before you send a simple log file that could very well help me pinpoint the issue as I assume the crash is a "domino" effect not the actual mod causing it. @GregoryMonteiro

**Comment by Luffyyy** [comment] 2021-08-05 22:09
Please try the latest commit in GitHub, an issue was fixed that could be the cause of this crash too.

**Comment by Luffyyy** [comment] 2021-08-07 11:30
due to OP not answering after many replies I will close this issue as I assume my changes fixed it. Open a new issue if I'm wrong. Please be active when reporting issues too.

**Closed by Luffyyy** 2021-08-07 11:30 UTC
Labels: crash

**Comment by himurabattousa** [comment] 2021-08-12 02:52
Sorry.
Thank you very much.
