### ISSUE TITLE
Can't Join in lobby

### ISSUE THREAD

**Issue by StopidChild** [simon-wh/PAYDAY-2-BeardLib#380] opened 2021-02-10 04:44 UTC
"steam could not authenticate steam id for host"
After deleting Beardlib, this thing disappears, Game don't Crash, Only this error.
If this question seems stupid, sorry

**Comment by StopidChild** [comment] 2021-02-10 06:06
In crashlog.txt and crash.txt nothing about this

**Comment by Luffyyy** [comment] 2021-02-10 12:10
It's not the first time I hear about this kind of issue but it's very hard to know the cause of it. It'll require me to test around with you bunch of code and even then I don't know if it'll help as much.

**Comment by StopidChild** [comment] 2021-02-11 03:23
> It's not the first time I hear about this kind of issue but it's very hard to know the cause of it. It'll require me to test around with you bunch of code and even then I don't know if it'll help as much.

Is there anything I can do to help solve this problem?

**Comment by Luffyyy** [comment] 2021-02-14 20:43
Add me on Discord and we'll try to debug it. If it happens constantly while testing I can look into what might be causing it.
-> Luffy#4754

**Comment by TheTrashOtaku04** [comment] 2021-10-01 16:06
Is there already a solution to this issue?

**Comment by Luffyyy** [comment] 2021-10-01 19:18
> 
> 
> Is there already a solution to this issue?

Nope. It's a very hard problem to fix as it's inconsistent as I said in the previous reply, I may be able to help debug it with someone that has the issue, but I can't promise this will be fixed.

**Comment by TheTrashOtaku04** [comment] 2021-10-01 21:00
> Nope. It's a very hard problem to fix as it's inconsistent as I said in the previous reply, I may be able to help debug it with someone that has the issue, but I can't promise this will be fixed.

could you help me solve the problem? or at least try?

**Comment by Luffyyy** [comment] 2021-10-02 13:56
> 
> > Nope. It's a very hard problem to fix as it's inconsistent as I said in the previous reply, I may be able to help debug it with someone that has the issue, but I can't promise this will be fixed.
> 
> could you help me solve the problem? or at least try?

Read my reply above, I offered people to add me on discord to attempt to fix it.

**Closed** 2021-10-05 19:02 UTC
Labels: bug, waiting

**Comment by Luffyyy** [comment] 2021-10-05 19:07
This issue is one of the oldest issues that has been finally fixed, I still have no idea why a select few got this issue but this is confirmed fixed or at least we discovered where this happens. I will update on whether this works for custom heists too (as what caused this was a function to make them work, I had to rethink the way it worked)
Related issues: #73, #212, #286, #390.

**Comment by Luffyyy** [comment] 2021-10-05 21:23
Custom heists confirmed working.
