### ISSUE TITLE
Hands disappearing

### ISSUE THREAD

**Issue by Rad1anT1327** [simon-wh/PAYDAY-2-BeardLib#625] opened 2023-03-03 14:57 UTC
If I create a lobby or join second after the host in his lobby, my hands will disappear after joining the third or fourth player to this lobby.

**Comment by segabl** [comment] 2023-05-10 13:29
Duplicate of https://github.com/simon-wh/PAYDAY-2-BeardLib/issues/617

**Closed** 2023-05-10 13:30 UTC
Labels: bug
