### ISSUE TITLE
Crashing when loading into heists + random crashing

### ISSUE THREAD

**Issue by Metal-Invitine** [simon-wh/PAYDAY-2-BeardLib#469] opened 2021-08-16 08:27 UTC
**Describe the crash**
A clear and concise description of what the crash is.
Game closes itself without warning, checking crash.txt reveals a access violation related to beardlib's resource manager, not sure what in beardlib is causing it.
**To Reproduce**
Launch a heist I guess? I'm really not sure what lua in beardlib is causing this.
**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6990807/crash.txt)
I've updated Beardlib and SuperBLT just in case and it hasn't fixed it, I've been crashing from this exact access violation ever since the 8th anniversary update started and each day it's gone from random crashing during heists to now always crashing when trying to load into any offline or online heist.
[2021_08_16_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6990824/2021_08_16_log.txt)
I've also made sure theres 100% no mods or overrides in incorrect folders, I'm wondering if maybe another mod might not be up to date and I'm getting another domino affect but, not sure.

**Comment by Metal-Invitine** [comment] 2021-08-16 10:29
Current thread: Main
Script stack:
load() lib/managers/dynamicresourcemanager.lua:151
_LoadAsset() @mods/BeardLib/Classes/Managers/FileManager.lua:236
LoadAsset() @mods/BeardLib/Classes/Managers/FileManager.lua:258
unit_data() @mods/BeardLib/Hooks/CoreSystem.lua:62
core/lib/managers/coresequencemanager.lua:681

Just to ask, with when it says "lua:number" does that refer to the line it's on within notepad? Cause if so, is there anyway to edit each individual line/ delete to see if that changes anything?

Cause if that's the case I'm able to find all luas excluding whatever "dynamicresourcemanger.lua" is.

**Comment by segabl** [comment] 2023-01-09 11:45
very late and I'm assuming this is fixed by now so I'll close this issue, but any mention of beardlib and dynamicresourcemanager is generally any mod making use of beardlib's addfiles module to add custom assets. so if you crash like this it's caused by another mod having a faulty asset or multiple mods overriding the same asset and causing some sort of dependency conflict.

**Closed by segabl** 2023-01-09 11:45 UTC
Labels: crash
