### ISSUE TITLE
Infinite loading screen, can't join mid-game

### ISSUE THREAD

**Issue by azalty** [simon-wh/PAYDAY-2-BeardLib#552] opened 2022-06-19 15:49 UTC
**Describe the bug**
- I get an infinite loading screen when in lobby with someone else (custom map) OR when starting a custom map (when we're all ready and on the difficulty screen & fade to black, it gets stuck here)
- People also sometimes can't join mid-game (tested on different custom maps).

Doesn't happen most of the time, but defo annoying.

**To Reproduce**
Seems to be random, I don't understand what causes this issue.

**Comment by segabl** [comment] 2022-06-20 09:20
Do you get the blackscreen while being the host or just as client? Sometimes loading of custom music can interfere with the game loading during blackscreen so check if it's caused by that.

**Comment by azalty** [comment] 2022-06-20 11:31
I was the host. If my friend leaved during the lobby to ready screen loading, it would fix it a couple of seconds later.

**Comment by segabl** [comment] 2022-06-21 07:24
Would be good to have a log of when this happens (mods/logs)

**Comment by segabl** [comment] 2022-10-16 22:53
Closing due to lack of information

**Closed by segabl** 2022-10-16 22:53 UTC
Labels: bug

**Comment by azalty** [comment] 2022-10-17 09:57
Oops didn't get the notification, I'll provide logs if it happens again
