### ISSUE TITLE
Game crashes after "Press any key" screen.

### ISSUE THREAD

**Issue by why-are-all-the-usernames-taken-sadface** [simon-wh/PAYDAY-2-BeardLib#438] opened 2021-07-31 12:12 UTC
Game crashes after "press any key" menu.
After pressing a key, the screen turns black with only a gray cursor visible, game proceeds to crash after 3-5 seconds.
(Possibly similiar to #436 ?)
Using latest release, latest SuperBLT, no other mods. Game stops crashing when BeardLib is removed.
 - Launch PAYDAY 2
 - Wait for the intro videos to finish/skip them
 - Press any key when the game prompts you to

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6911130/crash.txt)

**Comment by Luffyyy** [comment] 2021-07-31 13:14
A crash caused by 4.5 and fixed by 4.5.1. Delete mods/saves/BeardLib_Options.txt

**Closed** 2021-07-31 13:14 UTC
Labels: crash
