### ISSUE TITLE
Steam could not authenticate ID for Host

### ISSUE THREAD

**Issue by nothingbutyea** [simon-wh/PAYDAY-2-BeardLib#390] opened 2021-04-04 15:12 UTC
every time i join a pub game it pops up [Steam could not authenticate ID for Host] once i remove beardlib the problem has gone

**Comment by Luffyyy** [comment] 2021-04-08 21:06
Duplicate of #380.
Please avoid making duplicate issues and do not skip templates for issues. They help me help you. Unfortunately, as you can read in the other issue, this requires me to test with you. Some same thing I told them, applies to you go there.

**Closed by Luffyyy** 2021-04-08 21:06 UTC
Labels: bug

**Comment by nothingbutyea** [comment] 2021-04-14 12:48
i am so sorry about that as i didnt see the problem list clearly. thank you

Luffy ***@***.***> 於 2021年4月9日 週五 上午5:06寫道：
