### ISSUE TITLE
Crashing Randomly when people join or late into a heist

### ISSUE THREAD

**Issue by SALXAPHONE** [simon-wh/PAYDAY-2-BeardLib#505] opened 2021-12-21 18:20 UTC
I've been crashing a lot recently with the new Payday 2 Christmas update. I tried looking up anything related to my crash.txt in my files that other people might have had. The only thing I found was an old bug with crashing that related to armor skins whenever someone would join the lobby. I'm going to try playing with BeardLib disabled and if it's still crashing it must be a different mod.

**Comment by SALXAPHONE** [comment] 2021-12-21 18:22
It could also be because SuperBLT just updated as well.

**Comment by Luffyyy** [comment] 2022-09-22 15:44
Sorry for not replying, is this issue still relevant? Also make sure to include a crashlog when reporting issues and that you are sure it's caused by BeardLib.

**Comment by segabl** [comment] 2023-01-09 11:46
assuming this has been resolved by now, closing.

**Closed by segabl** 2023-01-09 11:46 UTC
