### ISSUE TITLE
Beardlib causes crash on press any key screen

### ISSUE THREAD

**Issue by pr00bing** [simon-wh/PAYDAY-2-BeardLib#462] opened 2021-08-08 02:27 UTC
**Describe the crash**
I get to the press any key screen and when i click it crashes the game, this is the only mod that causes this to happen in my game.

**To Reproduce**
check describe the crash

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6950122/crash.txt)

**Comment by Luffyyy** [comment] 2021-08-08 07:00
Did you update sblt?
I need also a blt log, you can find it in mods/logs.

**Comment by FailAndBail** [comment] 2021-08-10 01:57
I've had the same problem, I tried taking out all of my mods despite them working when I last played and found out that it was beardlib that was crashing it, here's my log
[2021_08_09_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6958393/2021_08_09_log.txt)

**Comment by FailAndBail** [comment] 2021-08-10 01:59
also i reinstalled sblt and all of my mods, including beardlib and still had the same problem

**Comment by T-S2-T** [comment] 2021-08-13 12:56
Im having the same issue and i just cant play is it possible to give the beardlib version before the hotfix so i can at least play

**Comment by T-S2-T** [comment] 2021-08-13 13:19
update: reinstalled super blt and the game opened =)
still donno what the problem was but this worked

**Comment by Luffyyy** [comment] 2021-08-13 13:24
> update: reinstalled super blt and the game opened =)
> still donno what the problem was but this worked 
> 

Outdated sblt likely

**Comment by 1Nomadz** [comment] 2021-08-16 21:14
I have the same problem, but i re-installed SuperBLT 2 Times already, no mods except beardlib. 
Here's the SBLT Log:
06:10:25 PM Log:  (C:\projects\payday2-superblt\src\debug\blt_debug.cpp:124) Command line: "F:\SteamLibrary\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
06:10:25 PM Log:  (C:\projects\payday2-superblt\platforms\w32\signatures\signatures.cpp:352) Scanning for signatures in payday2_win32_release.exe
06:10:25 PM Log:  (C:\projects\payday2-superblt\platforms\w32\signatures\signatures.cpp:405) Scanned for 57 signatures in 0 milliseconds with 0 cache misses
06:10:25 PM Log:  (C:\projects\payday2-superblt\src\dbutil\DB.cpp:127) Start loading DB info
06:10:26 PM WARNING:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:486) Wren base file not found, Wren VM disabled - the basemod may be corrupted
06:10:26 PM Log:  (C:\projects\payday2-superblt\src\dbutil\DB.cpp:242) Finished loading DB info: 246100 files in 751 ms
06:10:29 PM Log:  (C:\projects\payday2-superblt\src\util\compression.cpp:169) Extracting blt_basemod_download.zip to mods
06:11:06 PM Log:  (C:\projects\payday2-superblt\src\debug\blt_debug.cpp:124) Command line: "F:\SteamLibrary\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
06:11:06 PM Log:  (C:\projects\payday2-superblt\platforms\w32\signatures\signatures.cpp:352) Scanning for signatures in payday2_win32_release.exe
06:11:06 PM Log:  (C:\projects\payday2-superblt\platforms\w32\signatures\signatures.cpp:405) Scanned for 57 signatures in 16 milliseconds with 0 cache misses
06:11:06 PM Log:  (C:\projects\payday2-superblt\src\dbutil\DB.cpp:127) Start loading DB info
06:11:06 PM Log:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:49) [WREN] Loading module BeardLib/AssetLoader
06:11:06 PM Log:  (C:\projects\payday2-superblt\src\InitiateState.cpp:977) Initiating Hook
06:11:07 PM Log:  (C:\projects\payday2-superblt\src\dbutil\DB.cpp:242) Finished loading DB info: 246100 files in 791 ms
06:11:09 PM Log:  (C:\projects\payday2-superblt\src\InitiateState.cpp:977) Initiating Hook
06:11:09 PM Lua: [INFO] [BLT] Setup... 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTLogs 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTModManager 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTKeybindsManager 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTPersistScripts 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTLocalization 
06:11:09 PM Lua: [INFO] [BLT] Creating missing directory mods/downloads 
06:11:09 PM Lua: [INFO] [BLT] Creating missing directory mods/saves 
06:11:09 PM Lua: [INFO] [BLT] Cleaning logs folder, lifetime 1 day(s) 
06:11:09 PM Lua: [INFO] [BLT] Loading mods for state: table: 0x001c89e0 
06:11:09 PM Lua: [INFO] [BLT] Loading mod: base 
06:11:09 PM Lua: [INFO] [BLT] Loading mod: BeardLib 
06:11:09 PM Lua: [ERROR] Could not load file 'mods/saves/blt_data.txt', no data loaded... 
06:11:09 PM Lua: [INFO] [BLT] Setting up mod:  base 
06:11:09 PM Lua: [INFO] [BLT] Setting up mod:  BeardLib 
06:11:09 PM Log:  (C:\projects\payday2-superblt\src\InitiateState.cpp:977) Initiating Hook
06:11:09 PM Lua: [INFO] [BLT] Setup... 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTLogs 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTModManager 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTKeybindsManager 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTPersistScripts 
06:11:09 PM Lua: [INFO] [BLT] Loading module: BLTLocalization 
06:11:09 PM Lua: [INFO] [BLT] Cleaning logs folder, lifetime 1 day(s) 
06:11:09 PM Lua: [INFO] [BLT] Loading mods for state: table: 0x001c89c0 
06:11:09 PM Lua: [INFO] [BLT] Loading mod: base 
06:11:09 PM Lua: [INFO] [BLT] Loading mod: BeardLib 
06:11:09 PM Lua: [ERROR] Could not load file 'mods/saves/blt_data.txt', no data loaded... 
06:11:09 PM Lua: [INFO] [BLT] Setting up mod:  base 
06:11:09 PM Lua: [INFO] [BLT] Setting up mod:  BeardLib 
06:11:10 PM Log:  (C:\projects\payday2-superblt\src\InitiateState.cpp:977) Initiating Hook
06:11:10 PM Lua: [INFO] [BLT] Setup... 
06:11:10 PM Lua: [INFO] [BLT] Loading module: BLTLogs 
06:11:10 PM Lua: [INFO] [BLT] Loading module: BLTModManager 
06:11:10 PM Lua: [INFO] [BLT] Loading module: BLTKeybindsManager 
06:11:10 PM Lua: [INFO] [BLT] Loading module: BLTPersistScripts 
06:11:10 PM Lua: [INFO] [BLT] Loading module: BLTLocalization 
06:11:10 PM Lua: [INFO] [BLT] Cleaning logs folder, lifetime 1 day(s) 
06:11:10 PM Lua: [INFO] [BLT] Loading mods for state: table: 0x2a54aa20 
06:11:10 PM Lua: [INFO] [BLT] Loading mod: base 
06:11:10 PM Lua: [INFO] [BLT] Loading mod: BeardLib 
06:11:10 PM Lua: [ERROR] Could not load file 'mods/saves/blt_data.txt', no data loaded... 
06:11:10 PM Lua: [INFO] [BLT] Setting up mod:  base 
06:11:10 PM Lua: [INFO] [BLT] Setting up mod:  BeardLib 
06:11:16 PM Log:  (C:\projects\payday2-superblt\src\http\http.cpp:51) CURL_INITD
06:11:22 PM Log:  (C:\projects\payday2-superblt\src\http\http.cpp:57) CURL CLOSED

**Comment by Luffyyy** [comment] 2021-08-16 22:40
Please send the log as a file instead of pasting it into the textbox. Also include a crashlog, not every crash is the same.

**Comment by 1Nomadz** [comment] 2021-08-17 05:02
Nevermind, sorry for posting the log into the textbox, but i found the issue, it didnt occour to me that after cleaning the mods file the Super Duper Skin Swapper's skin changes to my guns would interfere after inserting beardlib again. Thanks for respoding, though.

**Comment by JackTheRipper2004** [comment] 2021-08-18 03:49
yea i got it aswell idk why i got the crash press any key bug

**Comment by segabl** [comment] 2022-06-22 21:02
Closing this as it is not caused by BeardLib

**Closed by segabl** 2022-06-22 21:02 UTC
Labels: crash
