### ISSUE TITLE
Game crashes after testing civilianspawner element

### ISSUE THREAD

**Issue by Anothuor** [simon-wh/PAYDAY-2-BeardLib#426] opened 2021-06-25 05:22 UTC
**Describe the crash**
Pd2 crashes after pressing 'test' in the civilian spawner element, and crashes whenever you try to join after.
Super annoying I worked for like 4 hours on a city and I just can't take this anymore

**To Reproduce**
What

**Crashlog**
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6713708/crashlog.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6713709/crash.txt)

**Comment by Luffyyy** [comment] 2021-06-25 05:36
1. This is beardlib not editor's repository.
2. Make sure auto saving is on in the editor if you don't want to lose hours of work. 
3. Steps to reproduce said issue. 
That being said, this is something that's already more or less fixed in a dev version of the editor. Unfortunately it's not ready yet. This happens due to the spawner trying to spawn a unit that isn't loaded. I'd recommend joining this discord server https://discord.gg/Th82W8M5 and asking other map makers about this.

**Closed by Luffyyy** 2021-06-25 05:36 UTC
Labels: crash
