### ISSUE TITLE
Crash upon accessing main menu

### ISSUE THREAD

**Issue by ZeroJyllmeiko** [simon-wh/PAYDAY-2-BeardLib#316] opened 2020-07-03 14:47 UTC
As soon as I can get on the main menu, as soon as I press a button, it crashes completely! It has just been updated for me, and it worked before a few minutes ago. Also deleted and reinstalled BeardLib and still bugged out.
crash.txt:

Application has crashed: C++ exception
[string "lib/managers/blackmarketmanager.lua"]:1360: attempt to index local 'equipped' (a nil value)

SCRIPT STACK

outfit_string() lib/managers/blackmarketmanager.lua:1574
_update_outfit_information() lib/managers/menumanagerpd2.lua:646
_on_modified_weapon() lib/managers/blackmarketmanager.lua:5016
modify_weapon() lib/managers/blackmarketmanager.lua:4957
buy_and_modify_weapon() lib/managers/blackmarketmanager.lua:4966
_cleanup_blackmarket() lib/managers/blackmarketmanager.lua:8830
verify_dlc_items() lib/managers/blackmarketmanager.lua:8365
give_dlc_and_verify_blackmarket() lib/managers/dlcmanager.lua:237
func() lib/managers/dlcmanager.lua:251
dispatch() core/lib/utils/coreevent.lua:212
_on_load_sequence_complete() lib/managers/savefilemanager.lua:255
update() lib/managers/savefilemanager.lua:240
update() lib/setups/setup.lua:857
update() lib/setups/menusetup.lua:352
update() @mods/base/lua/MenuSetup.lua:6
orig__update() core/lib/setups/coresetup.lua:557
trainer/tools/pubinfloopv2.lua:141

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.95.896
	CPU : Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[26.21.14.3086]
	Language : english
	Memory :     16257MB 28KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment] 2020-07-03 15:35
Install this https://modworkshop.net/mod/27575 then crash and send the cotent of mods/TroubleShooter/EnterHere as a zip file to here. You can zip it using software like 7zip.

**Comment by ZeroJyllmeiko** [comment] 2020-07-03 15:47
[EnterHere.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4870462/EnterHere.zip)

**Comment by Luffyyy** [comment] 2020-07-03 16:14
Doesn't seem like an issue I can reproduce in my end so I'll first check if this issue is due to 4.0.
Here's a link for 3.5: 
[BeardLib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4870559/BeardLib.zip)

If the issue is still present. It would be easier to work in Discord where I could test with you the exact cause. If it's a 4.0 issue I'll have to look into it.

**Comment by ZeroJyllmeiko** [comment] 2020-07-03 16:21
It works with 3.5, so I think it could be a 4.0 issue.

**Comment by Luffyyy** [comment] 2020-07-03 16:42
Hm... What mask did you have equipped?

**Comment by ZeroJyllmeiko** [comment] 2020-07-03 16:48
Unmasked. Comes from a mask mod.

**Comment by Jiqegolo2671** [comment] 2020-07-04 01:06
This was mine:

Application has crashed: C++ exception
[string "lib/managers/blackmarketmanager.lua"]:6186: attempt to index local 'switch_data' (a nil value)



SCRIPT STACK

_cleanup_blackmarket() lib/managers/blackmarketmanager.lua:8789
verify_dlc_items() lib/managers/blackmarketmanager.lua:8365
give_dlc_and_verify_blackmarket() lib/managers/dlcmanager.lua:237
func() lib/managers/dlcmanager.lua:251
dispatch() core/lib/utils/coreevent.lua:212
_on_load_sequence_complete() lib/managers/savefilemanager.lua:255
update() lib/managers/savefilemanager.lua:240
original() lib/setups/setup.lua:857
update() @mods/base/req/core/Hooks.lua:185
update() lib/setups/menusetup.lua:352
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.95.896
	CPU : Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[26.21.14.4587]
	Language : english
	Memory :     16346MB 900KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : C-MEDIA Inc. (Speakers (USB Advanced Audio Device))

**Comment by Jiqegolo2671** [comment] 2020-07-04 01:10
Fixed it by:

Renaming mod_overrides to mod_override
Deleting BeardLib and downloading a fresh, new one
Renaming mods to mod
Redownloading SuperBLT
Moving the new SuperBLT to mod
Renaming mod back to mods
Launching game
After launching, going to inventory and back so a new save was made
Closing the game, renaming mod_override back to mod_overrides and enjoy playing

(Hope it's detailed enough and you don't turn into a dishwasher or something)

**Comment by Luffyyy** [comment] 2020-07-04 02:46
Generally this would wipe your custom stuff so not exact solution

**Comment by Jiqegolo2671** [comment] 2020-07-04 21:46
Well atleast we can play the game that way, although I noticed that the performance worsened with 4.0:

4.0 loading time from lobby to heist prep screen: 2min 15s
3.5 loading time from lobby to heist prep screen: 53s

Both times were counted from fresh start and same heist.

**Comment by Luffyyy** [comment] 2020-07-05 01:20
I doubt it. Computers save cache and do tasks faster the 2nd time.

**Comment by Luffyyy** [comment] 2021-02-14 20:49
Too old. Remake issue if you experience this. I might be able to debug with you to find to culprit.

**Closed by Luffyyy** 2021-02-14 20:49 UTC
