### ISSUE TITLE
Beardlib causes a crash when attempting to open inventory

### ISSUE THREAD

**Issue by PimpWhiskers** [simon-wh/PAYDAY-2-BeardLib#550] opened 2022-06-15 21:09 UTC
When I have beardlib installed. If I attempt to open my inventory, by clicking the button. It instantly crashes. The crash log says it's because of a weapon component manager. Which I don't know what that means. So idk how to fix it. Taking beardlib out fixes it. But then maps and mods don't work because of it. 

Idk how to replicate, since I'm not sure if I'm the only one having the issue, installing it in the mods folder. opening the game, and clicking inventory 

Application has crashed: C++ exception
[string "lib/managers/menu/menucomponentmanager.lua"]:3812: attempt to index a nil value

SCRIPT STACK

sort() =[C]
create_weapon_mod_icon_list() lib/managers/menu/menucomponentmanager.lua:3804
las_pre_player_loadout_data() lib/managers/blackmarketmanager.lua:3825
player_loadout_data() @mods/Legendary Armour Skins/hooks/gui_hooks/blackmarketmanager.lua:3
init() lib/managers/menu/playerinventorygui.lua:172
new() core/lib/utils/coreclass.lua:35
_create_inventory_gui() lib/managers/menu/menucomponentmanager.lua:4003
create() lib/managers/menu/menucomponentmanager.lua:3992
set_active_components() lib/managers/menu/menucomponentmanager.lua:493
set_active_components() @mods/base/lua/MenuComponentManager.lua:18
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
__orig() lib/managers/menumanagerpd2.lua:20
__orig() @mods/MoreAFK/CommandManager/Addons/delaycall.lua:51
update() @mods/TheCooker/delaycall.lua:69
original() lib/setups/setup.lua:885
update() @mods/base/req/core/Hooks.lua:288
update() lib/setups/menusetup.lua:358
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.123.108
	CPU : Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3050 / nvldumd.dll[30.0.15.1215]
	Language : english
	Memory :     16298MB 724KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (2- Arctis 7 Game))

**Comment by segabl** [comment] 2022-06-15 21:33
It's probably caused by a faulty custom weapon or attachment mod, try removing any of those mod types and see if that fixes it

**Comment by segabl** [comment] 2022-10-16 22:54
Closing due to not being caused by Beardlib itself and lack of further information.

**Closed by segabl** 2022-10-16 22:54 UTC
Labels: crash
