### ISSUE TITLE
Body bags don't disappear when thrown in water

### ISSUE THREAD

**Issue by Smurfingaround** [simon-wh/PAYDAY-2-BeardLib#461] opened 2021-08-07 10:12 UTC
Hi, 
Really enjoy your work, but I've noticed there's a glitch where body bags when normally thrown in the water disappear, no longer does this. I'm not particularly sure if it's because of BeardLib but when I remove the mod, it seems to work fine.

**Comment by Luffyyy** [comment] 2021-08-07 11:07
Duplicate of #459

**Closed by Luffyyy** 2021-08-07 11:07 UTC
