### ISSUE TITLE
Crashes at 10 min

### ISSUE THREAD

**Issue by Kawwaka** [simon-wh/PAYDAY-2-BeardLib#639] opened 2023-04-17 03:04 UTC
any time after 10 minutes on the heist, the game crashes and i recive this log, i already take off almost every mod to test this, i dont know what could be but i know its related to the "Shield Marshall"

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:236  
                   LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:258  
                  spawn_unit()  @mods/BeardLib/Hooks/CoreSystem.lua:26              
          _spawn_head_gadget()  lib/units/enemies/cop/copdamage.lua:3194            
               damage_bullet()  lib/units/enemies/cop/copdamage.lua:702             
          give_impact_damage()  lib/units/weapons/raycastweaponbase.lua:2774        
                on_collision()  lib/units/weapons/raycastweaponbase.lua:2651        
               _fire_raycast()  lib/units/weapons/raycastweaponbase.lua:907         
                        fire()  lib/units/weapons/raycastweaponbase.lua:560         
                        fire()  @mods/BeardLib/Hooks/Fixes.lua:429                  
                        fire()  lib/units/weapons/newraycastweaponbase.lua:2034     
                    original()  lib/units/weapons/raycastweaponbase.lua:466         
                trigger_held()  @mods/base/req/core/Hooks.lua:288                   
                trigger_held()  lib/units/weapons/newraycastweaponbase.lua:2019     
_check_action_primary_attack()  lib/units/beings/player/states/playerstandard.lua:5141  
       _update_check_actions()  lib/units/beings/player/states/playerstandard.lua:1013  
                      update()  lib/units/beings/player/states/playerstandard.lua:447  
                    original()  lib/units/beings/player/playermovement.lua:279      
                                @mods/base/req/core/Hooks.lua:288

**Comment by segabl** [comment] 2023-04-18 09:41
Well since you know it's related to the shield marshal, you should check any mod that modifies their model, as thats whats most likely causing the crash (BeardLib trying to load its assets but they are broken)

**Comment by segabl** [comment] 2023-04-27 11:50
either caused by a mod or conflict between two mods, not beardlib itself, closing this

**Closed by segabl** 2023-04-27 11:50 UTC
Labels: crash
