### ISSUE TITLE
Crash "Application has crashed: access violation"

### ISSUE THREAD

**Issue by GregoryMonteiro** [simon-wh/PAYDAY-2-BeardLib#445] opened 2021-07-31 22:22 UTC
You updated and this error started to happen.

`Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:236  
                   LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:258  
             safe_spawn_unit()  @mods/BeardLib/Hooks/CoreSystem.lua:26              
                        init()  core/lib/managers/mission/coreelementunitsequence.lua:10  
                         new()  core/lib/utils/coreclass.lua:35                     
            _create_elements()  core/lib/managers/mission/coremissionmanager.lua:457  
                        init()  core/lib/managers/mission/coremissionmanager.lua:403  
                         new()  core/lib/utils/coreclass.lua:35                     
itr_original_missionmanager_addscript()  core/lib/managers/mission/coremissionmanager.lua:113  
                 _add_script()  @mods/Iter/lua/coremissionmanager.lua:401           
          _load_mission_file()  core/lib/managers/mission/coremissionmanager.lua:107  
                       parse()  core/lib/managers/mission/coremissionmanager.lua:78  
                   init_game()  lib/setups/gamesetup.lua:684                        
                                core/lib/setups/coresetup.lua:422                   

-------------------------------

System information:
	Application version : 1.107.25
	CPU : Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics 620 / igdumdim32.dll[27.20.100.9416]
	Language : english
	Memory :     16314MB 920KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Auscultadores (em006))

`

**Comment by Luffyyy** [comment] 2021-07-31 23:00
Duplicate of #439 please explain in better detail **there**.

**Closed by Luffyyy** 2021-07-31 23:00 UTC
Labels: crash
