### ISSUE TITLE
Crash after start game

### ISSUE THREAD

**Issue by FoksWolker** [simon-wh/PAYDAY-2-BeardLib#134] opened 2018-03-10 15:18 UTC
Sat Mar 10 20:05:40 2018

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  149                                                 
                      update()  174                                                 
                        func()  @mods/BeardLib/BeardLibCore.lua:147                 
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                      update()  @mods/base/lua/MenuSetup.lua:7                      
                                core/lib/setups/coresetup.lua:540                   

-------------------------------

System information:
	Application version : 1.87.537.
	CPU : Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 550 Ti / nvd3dum.dll[22.21.13.8494]
	Language : russian
	Memory :     3959MB 52KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft High Definition Audio))

**Comment by Luffyyy** [comment] 2018-03-10 19:10
Missing information, there's no proof that BeardLib is the cause of the crash.
I will close the issue. But, if you want, I can try finding out why it happens, I need a BLT log(you can get it from mods/logs/ and a text file with the crash/play date)

**Closed by Luffyyy** 2018-03-10 19:10 UTC
