### ISSUE TITLE
all of my mods and mod overrides not working with new beardlib update

### ISSUE THREAD

**Issue by vortexagent** [simon-wh/PAYDAY-2-BeardLib#452] opened 2021-08-03 12:01 UTC
after the new 4.52 update it started to crash my game i removed all my mods other then superblt and beardlib then it started to work i don't know how to fix this so does anyone know?

**Comment by connieprice** [comment] 2021-08-03 12:29
Duplicate of #451

**Closed** 2021-08-03 14:19 UTC
Labels: bug
