### ISSUE TITLE
After installing the mod, my shotguns began to throw bodies more strongly

### ISSUE THREAD

**Issue by T4GG3D** [simon-wh/PAYDAY-2-BeardLib#538] opened 2022-05-09 14:44 UTC
Hi
After installing the mod, my shotguns began to throw bodies more strongly. Can I fix it?

**Comment by segabl** [comment] 2022-06-02 22:52
Can you confirm this is caused by BeardLib?

**Comment by Luffyyy** [comment] 2022-09-22 15:40
No reply, closing.

**Closed by Luffyyy** 2022-09-22 15:40 UTC
Labels: bug, waiting
